-- Query para crear la tabla de solicitudes de viaje (Versión Pública con ID Secuencial)
DROP TABLE IF EXISTS solicitudes_viaje;

CREATE TABLE solicitudes_viaje (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id), -- Nullable para usuarios no logueados
  nombre_solicitante TEXT NOT NULL,
  cargo TEXT NOT NULL,
  area TEXT NOT NULL,
  jefe TEXT NOT NULL,
  tipo_viaje TEXT CHECK (tipo_viaje IN ('Nacional', 'Exterior')) NOT NULL,
  origen TEXT NOT NULL,
  destino TEXT NOT NULL,
  fecha_ida DATE NOT NULL,
  fecha_regreso DATE NOT NULL,
  necesita_tiquete BOOLEAN DEFAULT FALSE,
  necesita_hospedaje BOOLEAN DEFAULT FALSE,
  solicito_anticipo BOOLEAN DEFAULT FALSE,
  monto_anticipo DECIMAL(12, 2) DEFAULT 0,
  aprobador TEXT NOT NULL,
  centro_costos TEXT NOT NULL,
  observaciones TEXT,
  estado TEXT DEFAULT 'Pendiente' CHECK (estado IN ('Pendiente', 'Aprobado', 'Rechazado')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS
ALTER TABLE solicitudes_viaje ENABLE ROW LEVEL SECURITY;

-- Permitir que CUALQUIERA (incluyendo no logueados) inserte solicitudes
CREATE POLICY "Public can insert travel requests" ON solicitudes_viaje
  FOR INSERT WITH CHECK (true);

-- Permitir ver solicitudes (Ajustar según necesidad de privacidad)
-- Por ahora, permitimos que usuarios logueados vean las suyas y las públicas (user_id is null)
CREATE POLICY "Users can view requests" ON solicitudes_viaje
  FOR SELECT USING (auth.uid() = user_id OR user_id IS NULL OR auth.role() = 'authenticated');
